version: '3'
services:
    web:
        build: .
        volumes:
            - .:/nest_app
        command: npm run start:dev
        ports:
            - '3000:3000'
        depends_on:
            - mongo_db
    mongo_db:
        image: mongo:4
        volumes:
            - mongo_data:/data/db
volumes:
    mongo_data:
        driver: local
